services:
  tailscale:
    container_name: tailscale-pbx
    image: tailscale/tailscale:latest
    ports:
      - "8443:8443"
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "10000-10800:10000-10800/udp"
    hostname: miko # Your favorite Host Name
    privileged: true
    environment:
    - TS_AUTHKEY=$TS_AUTHKEY
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_USERSPACE=false
    cap_add:
      - net_admin
      - sys_module

  mikopbx:
    container_name: "mikopbx"
    build:
      context: .
      dockerfile: Dockerfile.mikopbx
    image: "ghcr.io/m-tsuru/mikopbx-tkytel-quickstart"
    network_mode: "container:tailscale-pbx"
    cap_add:
      - NET_ADMIN
    entrypoint: "/sbin/docker-entrypoint"
    volumes:
      - /var/spool/mikopbx/cf:/cf
      - /var/spool/mikopbx/storage:/storage
    tty: true
    environment:
      - ID_WWW_USER=${ID_WWW_USER}
      - ID_WWW_GROUP=${ID_WWW_GROUP}
      # Change the station name through environment variables
      - PBX_NAME=$YOUR_PBX_NAME
      # Change the default SSH port to 23
      - SSH_PORT=23
      # Change the default WEB port to 8080
      - WEB_PORT=8080
      # Change the default WEB HTTPS port to 8443
      - WEB_HTTPS_PORT=8443
      # MikoPBX Admin Console Password
      - WEB_ADMIN_PASSWORD=$MIKOPBX_ADMIN_PASSWORD
    depends_on:
      - tailscale
